spring:
  redis:
    host: 127.0.0.1
    port: 6379
    #连接超时时间(毫秒)
    timeout: 2000
    pool:
      #最大连接数(负数表示没有限制)
      max-active: 100
      #最大空闲连接
      max-idle: 10
      #最大阻塞等待时间(负数表示没有限制)
      max-wait: 100000
    database: 0


