server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://111.231.188.213:3306/merchant?useUnicode=true&characterEncoding=utf8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    schema-username: root
    schema-password: root
    data-username: root
    data-password: root
    platform: mysql
    schema: classpath:schema.sql # schema.sql中一般存放的是DDL脚本，即通常为创建或更新库表的脚本
    initialization-mode: always
    #continue-on-error: true
    batch:
      initialize-schema: always
  jpa:
    hibernate:
    #  ddl-auto: create-drop # 如果使用initialization-mode 则禁用ddl-auto
    show-sql: true  #data: classpath:data.sql # data.sql中一般是DML脚本，即通常为数据插入脚本
    properties:
      hibernate:
        globally_quoted_identifiers: true